
/* schema file for combat database
    authors: Lucas Burdell 
*/

CREATE TABLE entitydata (
    ENTITY_NAME VARCHAR(128) NOT NULL PRIMARY KEY,
    ENTITY_HEALTH INTEGER NOT NULL,
    ENTITY_MELEE_MODIFIER FLOAT NOT NULL,
    ENTITY_RANGED_MODIFIER FLOAT NOT NULL,
    ENTITY_VERBAL_MODIFIER FLOAT NOT NULL,
    INSULT_IMMUNITY BOOLEAN NOT NULL
)